INSERT INTO TEST03.TBL_LT_HIS 
SELECT *
FROM TEST01.TBL_LT_HIS A
WHERE NOT EXISTS (
      SELECT *
      FROM TEST02.TBL_LT_HIS IA
      WHERE IA.FA_ID = A.FA_ID
      AND IA.LT_ID = A.LT_ID
      AND IA.PROD_ID = A.PROD_ID
      AND IA.TIMEKEY = A.TIMEKEY)      
UNION ALL
SELECT *
FROM TEST02.TBL_LT_HIS A
WHERE NOT EXISTS (
      SELECT *
      FROM TEST01.TBL_LT_HIS IA
      WHERE IA.FA_ID = A.FA_ID
      AND IA.LT_ID = A.LT_ID
      AND IA.PROD_ID = A.PROD_ID
      AND IA.TIMEKEY = A.TIMEKEY)
UNION ALL
SELECT *
FROM TEST01.TBL_LT_HIS A
WHERE EXISTS (
      SELECT *
      FROM TEST02.TBL_LT_HIS IA
      WHERE IA.FA_ID = A.FA_ID
      AND IA.LT_ID = A.LT_ID
      AND IA.PROD_ID = A.PROD_ID
      AND IA.TIMEKEY = A.TIMEKEY
      AND IA.STAT_TYP = A.STAT_TYP)   
UNION ALL
SELECT *
FROM TEST01.TBL_LT_HIS A
WHERE EXISTS (
      SELECT *
      FROM TEST02.TBL_LT_HIS IA
      WHERE IA.FA_ID = A.FA_ID
      AND IA.LT_ID = A.LT_ID
      AND IA.PROD_ID = A.PROD_ID
      AND IA.TIMEKEY = A.TIMEKEY
      AND (
         (IA.STAT_TYP = 'RESERVE' AND A.STAT_TYP = 'LOADING')
      OR (IA.STAT_TYP = 'SELEECT' AND A.STAT_TYP = 'PROCESS')
      OR (IA.STAT_TYP = 'PROCESS' AND A.STAT_TYP = 'RESERVE')
      OR (IA.STAT_TYP = 'LOADING' AND A.STAT_TYP = 'SELEECT')
      )      
      )
UNION ALL
SELECT *
FROM TEST02.TBL_LT_HIS A
WHERE EXISTS (
      SELECT *
      FROM TEST01.TBL_LT_HIS IA
      WHERE IA.FA_ID = A.FA_ID
      AND IA.LT_ID = A.LT_ID
      AND IA.PROD_ID = A.PROD_ID
      AND IA.TIMEKEY = A.TIMEKEY
      AND (
         (IA.STAT_TYP = 'RESERVE' AND A.STAT_TYP = 'LOADING')
      OR (IA.STAT_TYP = 'SELEECT' AND A.STAT_TYP = 'PROCESS')
      OR (IA.STAT_TYP = 'PROCESS' AND A.STAT_TYP = 'RESERVE')
      OR (IA.STAT_TYP = 'LOADING' AND A.STAT_TYP = 'SELEECT')
      )      
      );
